name: fanxange
description: "A Place where you can buy or sell your favourite players and earn the cash."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  provider: ^6.1.1
  google_fonts: ^6.1.0
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.6.0
  intl: ^0.19.0
  fl_chart: ^0.66.1
  syncfusion_flutter_charts: ^24.2.3+1
  chart_sparkline: ^1.0.15+1
  dio: ^5.4.0
  flutter_countdown_timer: ^4.1.0
  skeletonizer: ^1.1.0
  fluttertoast: ^8.2.4
  shared_preferences: ^2.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
     - assets/svg/
     - assets/images/
     - assets/icons/
  #   - images/a_dot_ham.jpeg